### ISSUE TITLE
Perfomance issues

### ISSUE THREAD

**Issue by rogachevav** [zigawick/scheduler#5]
[database.cpp:9]  Variable 'm_groups' is assigned in constructor body. Consider performing initialization in initialization list.
[database.cpp:10] Variable 'm_teachers' is assigned in constructor body. Consider performing initialization in initialization list too.

**Comment by blumix** [comment]
it's a unique_ptr !

**Comment by rogachevav** [comment]
it's code review, beach (пляж)

**Comment by uburuntu** [comment]
**OPEN IT**
